server:
  port: 9101
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    primary:
      url: jdbc:mysql://127.0.0.1:3306/springsecurity-demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
      initialSize: 5      #初始化大小
      minIdle: 0       #最小闲置
      #maxIdle: 10     #最大闲置（已被druid官方弃用）
      maxActive: 300      #最大
      maxWait: 60000      #配置获取连接等待超时的时间
      timeBetweenEvictionRunsMillis: 60000        #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      minEvictableIdleTimeMillis: 300000          #配置一个连接在池中最小生存的时间，单位是毫秒
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      #打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall      #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙，eg:stat,wall,log4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000      #通过connectProperties属性来打开mergeSql功能；慢SQL记录
      useGlobalDataSourceStat: true       #合并多个DruidDataSource的监控数据
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    timeout: 5000
    lettuce:
      pool:
        max-active: 8     # 连接池最大连接数，默认8
        max-wait: -1      # 连接池最大阻塞等待时间，使用负值表示没有限制， 默认-1
        max-idle: 8        # 连接池中的最大空闲连接，默认8
        min-idle: 0         # 连接池中的最小空闲连接，默认0
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# RememberMeProperties配置
remember-me:
  parameterName: rememberMe

logging:
  level:
    com.iefihz.dao: debug